"""
Tests for the pipeline task chain (app/workers/tasks.py) — Parts 4b and 4c.

Unlike test_video_upload.py, this doesn't need Postgres, Redis, or a
running worker: Celery's `task_always_eager` setting runs tasks
synchronously, in-process, the moment they're dispatched, and the DB layer
points at a throwaway SQLite file instead of Postgres — same ORM models
and sync session code (app.core.database.get_sync_db), different driver
(fixtures in conftest.py). That's enough to prove both the chain wiring
(4b) and the status/current_stage/error_message writes (4c) actually
happen, without needing the full docker-compose stack.

What this does NOT verify: real async dispatch through Redis to a separate
worker process, or Postgres-specific behavior. Run against the full stack
for that — see tests/test_pipeline_worker_e2e.py (Part 4e).
"""

import uuid

import pytest

import app.workers.tasks as tasks_module
from app.models.enums import VideoStatus
from app.models.video import Video
from app.workers.celery_app import celery_app
from app.workers.tasks import (
    analyze_stage,
    detect_stage,
    done_stage,
    process_video,
    track_stage,
    validate_stage,
)
from conftest import seed_video


# --- Part 4b: chain wiring -------------------------------------------------


def test_process_video_dispatches_without_error(sqlite_session):
    # No seeded row: this test only checks the chain runs and returns the
    # right shape. _set_video_progress logging "not found" and moving on
    # (rather than raising) is exactly what's covered by
    # test_missing_video_does_not_raise below.
    result = process_video.apply(args=["video-123"])
    assert result.successful()
    assert result.get() == {"video_id": "video-123"}


def test_each_stage_is_a_pass_through_no_op(sqlite_session):
    """
    Every stage should return its payload completely unchanged. This is the
    contract Parts 5-9 build on: swapping a stage's no-op body for real CV
    logic must not change what keys later stages can expect to find.
    """
    payload = {"video_id": "video-456"}
    for stage in (validate_stage, detect_stage, track_stage, analyze_stage, done_stage):
        result = stage.apply(args=[payload])
        assert result.successful()
        assert result.get() == payload


def test_stages_are_registered_as_named_celery_tasks():
    """
    Named tasks (not autogenerated dotted-path names) matter here: retry
    policies and routing to GPU vs CPU queues (later Parts) target a stage
    by name.
    """
    expected_names = {
        "pipeline.validate",
        "pipeline.detect",
        "pipeline.track",
        "pipeline.analyze",
        "pipeline.done",
        "process_video",
    }
    assert expected_names.issubset(set(celery_app.tasks.keys()))


# --- Part 4c: status transitions + progress tracking ------------------------


def test_full_chain_ends_done_with_stage_cleared(sqlite_session, real_yolo_required):
    video_id = seed_video(sqlite_session)

    result = process_video.apply(args=[video_id])
    assert result.successful()

    with sqlite_session() as s:
        video = s.get(Video, uuid.UUID(video_id))
        assert video.status == VideoStatus.DONE
        assert video.current_stage is None
        assert video.error_message is None


def test_a_failing_stage_leaves_video_failed_not_done(sqlite_session, real_yolo_required):
    """
    Simulates a future stage (e.g. Part 6's `track`) raising, using the
    STAGE_FN_OVERRIDES test seam (Part 4d) rather than patching run_stage
    itself — this exercises the real retry-then-fail logic in run_stage,
    not a stand-in for it. Confirms: after exhausting retries, status ends
    FAILED (never DONE), current_stage records which stage failed,
    error_message is populated, and the chain doesn't proceed past it.

    Needs real_yolo_required: `track` isn't overridden until *after*
    `validate` and `detect` — both real now (Parts 5a/5d) — have already
    run for real ahead of it in the chain.
    """
    video_id = seed_video(sqlite_session)

    def always_fails(payload):
        raise RuntimeError("simulated tracking failure")

    tasks_module.STAGE_FN_OVERRIDES["track"] = always_fails
    try:
        # Eager mode retries synchronously (no real countdown wait), so this
        # runs to exhaustion fast: pipeline_max_retries + 1 total attempts.
        with pytest.raises(RuntimeError, match="simulated tracking failure"):
            process_video.apply(args=[video_id])
    finally:
        tasks_module.STAGE_FN_OVERRIDES.pop("track", None)

    with sqlite_session() as s:
        video = s.get(Video, uuid.UUID(video_id))
        assert video.status == VideoStatus.FAILED
        assert video.current_stage == "track"
        assert "simulated tracking failure" in video.error_message
        expected_attempts = tasks_module.settings.pipeline_max_retries + 1
        assert f"failed after {expected_attempts} attempt(s)" in video.error_message


def test_missing_video_does_not_raise(sqlite_session):
    """A video_id with no matching row shouldn't blow up the task — see
    the docstring on _set_video_progress for why this logs instead of raising."""
    fake_id = str(uuid.uuid4())
    result = process_video.apply(args=[fake_id])
    assert result.successful()
