"""initial schema

Revision ID: 51bdcc8a1557
Revises: 
Create Date: 2026-08-04 09:22:14.244992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bdcc8a1557'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLAYER', 'COACH', 'CLUB_ADMIN', 'ORGANIZER', 'BROADCASTER', name='user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('matches',
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlights',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LONG_RALLY', 'WINNING_SHOT', 'SPECTACULAR_SAVE', 'MATCH_POINT', 'BREAK_POINT', 'FAST_EXCHANGE', 'POWERFUL_SMASH', name='highlight_type'), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('clip_file_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_players',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_table('predictions',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('prediction_type', sa.Enum('WIN_PROBABILITY', 'MOMENTUM_SHIFT', 'FATIGUE', 'STRONGEST_PLAYER', 'WEAKEST_PLAYER', 'MOST_CONSISTENT_PLAYER', 'SHOT_SUCCESS_PROBABILITY', 'PERFORMANCE_TREND', name='prediction_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('match_time_seconds', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reels',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='reel_status'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('music_track', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('stat_type', sa.Enum('TOTAL_POINTS', 'WINNERS', 'ERRORS', 'SERVE_PERCENTAGE', 'RALLY_LENGTH_AVG', 'NET_SUCCESS_RATE', 'SMASH_SUCCESS_RATE', 'DISTANCE_COVERED', 'MOVEMENT_SPEED_AVG', 'LONGEST_RALLY', 'REACTION_TIME_AVG', 'MOMENTUM_POSSESSION', name='stat_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'DONE', 'FAILED', name='video_status'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('reel_highlights',
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('highlight_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.PrimaryKeyConstraint('reel_id', 'highlight_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_highlights')
    op.drop_table('videos')
    op.drop_table('statistics')
    op.drop_table('reports')
    op.drop_table('reels')
    op.drop_table('predictions')
    op.drop_table('match_players')
    op.drop_table('highlights')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
